### ISSUE TITLE
Issue : Provisioner log files created as nobody

### ISSUE THREAD

**Issue by shubham-gupta-28** [choria-io/provisioner#164]
One of our service was not able to read the provisioner log file, we noticed it was created as nobody.

Please don't make configuration or log files as nobody.

-rw-r----- 1 nobody nobody 575897 Apr  6 16:20 choria-provisioner.log

**Comment by ripienaar** [comment]
I am not a fan at all of these logs being world readable, but made it 644 which is the actual problem you encountered, also fixed the nobody though.
